### ISSUE TITLE
Add UC San Diego

### ISSUE THREAD

**Issue by danrschlosser** [CampusData/campusdata.github.io#17]
Data is on the Drive

**Comment by hydrosquall** [comment]
Perhaps add link to the folder on Google Drive here on Github, and/or replace the link to [initiatives](https://docs.google.com/document/d/14H5Vd4_235ZRLRK1XVzzyf_S4F6u2APs1QOUdVCOBwg/edit#heading=h.sylb8et6ouvb) from the 'welcome message' in Google Groups to Drive.

**Comment by hydrosquall** [comment]
Handled in this commit: https://github.com/CampusData/campusdata.github.io/commit/f7197f7b8aa7c8fde133e6743bf0283fb91726ad
