### ISSUE TITLE
umd orgs

### ISSUE THREAD

**Issue by jhil** [CampusData/campusdata.github.io#26]
add Technica (http://gotechnica.org/) as hackathon w/ bitcamp. add Startup Shell (http://startupshell.org/) as open data initiative.

**Comment by hydrosquall** [comment]
Currently each uni can only list 1 hackathon, perhaps a static page could be set up that links to both Technica and Bitcamp separately?

**Comment by jhil** [comment]
@hydrosquall Gotcha. Could we still add Startup Shell?

**Comment by hydrosquall** [comment]
I added Startup Shell in Pull #33 , and left Bitca.mp intact.

**Comment by jhil** [comment]
Cool!

**Comment by hydrosquall** [comment]
(re-open if we think of a way to incorporate both technica and bitcamp)
